# Generated by Django 5.0.1 on 2024-02-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_property_price_alter_property_status'),
        ('landlord', '0001_initial'),
        ('tenant', '0003_alter_tenant_groups_alter_tenant_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='lease_end_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='lease_start_date',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='property_leased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_property_leased', to='base.property'),
        ),
        migrations.CreateModel(
            name='LeaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_terms', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Active', 'Active')], default='Active', max_length=15)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.landlord')),
                ('property_leased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_leases', to='base.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_leases', to='tenant.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='lease_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_lease_info', to='tenant.leaseinfo'),
            preserve_default=False,
        ),
    ]
